# Generated by Django 4.2.27 on 2025-12-30 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('jenis', models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri'), ('campur', 'Campur')], max_length=10)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fasilitas', models.TextField()),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='kost_images/')),
                ('tersedia', models.BooleanField(default=True)),
                ('jumlah_kamar', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyewa', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('durasi_bulan', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kost_app.kost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
