# Generated by Django 6.0 on 2026-01-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kost_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ktp',
            field=models.ImageField(blank=True, help_text='Upload foto KTP Anda', null=True, upload_to='ktp_images/'),
        ),
    ]
